### ISSUE TITLE
404 with Custom Domain

### ISSUE THREAD

**Issue by antonengelhardt** [roqtech/roq-kickstarter-nextjs#4]
Hello,

i was trying to set up a Custom Domain after following the Kickstarter Guide. However, when i export the new env config and run the application on localhost, i get an 404 error, when i click on "Register" or "login". 

The [documentation](https://docs.roq.tech/authentication/advanced-topics/custom-domain) is not providing any further steps.

The CNAME is set correctly: [DNSChecker](https://dnschecker.org/#CNAME/e2e-chat.antonengelhardt.com) and the DNS Check also succeeds in the console. 

Also, i tried to help myself with your other repos and i think its also broken on [this](https://roq-kickstarter-b491b1c0q-roqtech.vercel.app/login) one. 

Am i missing something?

**Comment by praveenkokaroq** [comment]
Hi @antonengelhardt, right now it takes a little while for our SSL certs to be generated - up to a half day at max (for non production environments). We have an issue in our backlog that will make this nearly instant. 

For the moment, if it's blocking you I would recommend to switch back to the default domain temporarily, and we'll let you know when the SSL cert is deployed. 

Also - we have a Slack community where you could get quick responses and help. Feel free to join us here https://join.slack.com/t/roq-community/shared_invite/zt-1ldjz6vja-Ikr6TVmDfJ2fPk_RB83NTg

**Comment by antonengelhardt** [comment]
@praveenkokaroq Thanks for the reply. No, its not urgent. I will check again tomorrow then. 

Let me join the Slack Community. But your reply was already pretty fast ⚡

**Comment by praveenkokaroq** [comment]
Verified that it's provisioned now btw. Good luck!

**Comment by antonengelhardt** [comment]
@praveenkokaroq Thanks. The redirect actually works now.

But then i get: 
![Screenshot-Google Chrome-001788](https://user-images.githubusercontent.com/106314688/234936936-e5234057-8f9d-4b47-b628-377edb259455.png)

Do you have an idea?

**Comment by antonengelhardt** [comment]
I guess its related to [this](https://roq-community.slack.com/archives/C04CKEC58GZ/p1682597266746909)?

**Comment by praveenkokaroq** [comment]
@antonengelhardt the issue is that you have the same custom domain configured on two different environments. It's not explicitly documented, but we only support one custom domain per environment, otherwise it doesn't know which environment to use when you land on the auth page

**Comment by antonengelhardt** [comment]
@praveenkokaroq Thanks. It's working now 👍🏻
